services:
  - type: web
    name: insurance-backend
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn backend.api:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: GOOGLE_API_KEY
        sync: false  # You'll add this manually in Render dashboard
      - key: PYTHON_VERSION
        value: 3.11.0
    healthCheckPath: /
